# Generated by Django 2.0.3 on 2018-03-26 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpapp', '0005_auto_20180324_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_student', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpapp.Schools')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpapp.Sections')),
                ('std', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kpapp.Classes')),
            ],
        ),
    ]
