# Generated by Django 2.0.3 on 2018-03-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpapp', '0008_auto_20180330_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
