# Generated by Django 2.0.3 on 2018-04-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpapp', '0010_auto_20180403_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_obj',
            name='roll_no',
        ),
    ]
