# Generated by Django 2.0.3 on 2018-04-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpapp', '0011_remove_student_obj_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_obj',
            name='roll_no',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
