# Generated by Django 2.0.3 on 2018-04-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpapp', '0012_student_obj_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_obj',
            name='resume',
        ),
    ]
