# Generated by Django 2.0.3 on 2018-04-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpapp', '0013_remove_student_obj_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_obj',
            name='resume',
            field=models.FileField(default=2, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
