# Generated by Django 2.0.3 on 2018-04-03 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpapp', '0014_student_obj_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_obj',
        ),
    ]
